spring:
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/c?useUnicode=true&characterEncoding=utf-8
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template: true
    encoding: UTF-8
    servlet:
      content-type:  text/html
    mode: HTML5
    
jpa:
       hibernate:
         ddl-auto: update
         show-sql: true